### PR TITLE
full rewrite. Minimal allocations, documentation WIP

### PR DESCRIPTION
**Pull request by CordlessCoder**
I saw this library and decided that I wanted to use it, but thought it could be improved slightly.
Original benchmarking results:
image
Rewrite:
image

### CODE REVIEW

**Comment by CordlessCoder** [comment]
Can I publish this as a separate crate with credits to you from inspiration? Because I kinda got carried away and rewrote the entire codebase without reusing anything

**Comment by CordlessCoder** [comment]
Shaved off another 140 ns from sentence generation
image

**Comment by CordlessCoder** [comment]
image
Factored out the time it takes to generate the random SentenceConfig

**Comment by merelymyself** [comment]
To be honest, this is pretty insanely impressive. I originally made this project just to try out Rust and then got distracted with other projects to contribute to. I've taken a brief look through your code and it looks fine. Whether you want to publish it separately or merge it into the existing crate, both courses of action are fine by me; just let me know here, thanks.

**Comment by CordlessCoder** [comment]
Merging into the existing crate would be great

**Pull request merged**
